### ISSUE TITLE
Debugging error handling

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-clients#13]
I'm currently trying to update a project using the old client (raw JS files) and have utilized graphhopper-client.js but I'm getting:

```
Unhandled rejection [11]</GHUtil.prototype.extractError@http://localhost:9000/js/graphhopper-client.js:33:792
[16]</GraphHopperOptimization.prototype.doRawRequest/</<@http://localhost:9000/js/graphhopper-client.js:47:1505
[4]</Request.prototype.callback@http://localhost:9000/js/graphhopper-client.js:15:5622
Request/<@http://localhost:9000/js/graphhopper-client.js:15:2198
[2]</Emitter.prototype.emit@http://localhost:9000/js/graphhopper-client.js:9:1093
[4]</Request.prototype._end/t.onreadystatechange@http://localhost:9000/js/graphhopper-client.js:15:6965
```
  
I think here is something wrong in the client but could also be in my usage. How do I create and associate a map file for debugging?

**Comment by boldtrn** [comment]
Is this issue about our handwritten js client?

I yes, the issue sounds like you haven't created a catch function on the client side?

```
    ghRouting.doRequest()
      .then(function(json) {
        // Add your own result handling here
        console.log(json);
      })
      .catch(function(err) {
        console.error(err.message);
      });
```

**Comment by karussell** [comment]
Yes, thanks, will try. (We do not have an automated for JS IMO?)

**Comment by boldtrn** [comment]
> We do not have an automatically created for JS IMO?

What do you mean with that? An automated error handling? No, I think it makes more sense, that the client receives the error and can handle it appropriate. Adding catch blocks to Promises is [pretty standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises).

AFAIK it's similar to how Exception handling happens in Java. Once you catch it, it's caught. You need to re-throw it to propagate the Exception.

**Comment by karussell** [comment]
You asked if this is about our handwritten js client and I meant that we only have this handwritten one IMO

**Comment by boldtrn** [comment]
Ah, now I understand your reply :). I was just wondering because you opened the issue in the repository that contains the generated clients.

**Comment by karussell** [comment]
Ah, ups. Sorry - didn't notice this! Have created a new one at the correct place: https://github.com/graphhopper/directions-api-js-client/issues/35
