### ISSUE TITLE
R client

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-clients#15]
Currently only supported from the master branch of swagger codegen. See the created project here: https://github.com/graphhopper/directions-api-clients/tree/master/r

Will close here when the official swagger codegen release is reported to be usable.

**Comment by Anyaoha** [comment]
Can someone help me on how to install the graphhopper in R. 
I get the following error : Error: Could not find package root. when I tried the "library(devtools)
install(".")"

I want to plot routes of multiple nodes starting from an origin through several destinations and ending in the same origin. 

Thanks\

**Comment by crazycapivara** [comment]
@Anyaoha you may also check/test [crazycapivara/graphhopper-r](https://github.com/crazycapivara/graphhopper-r).
