### ISSUE TITLE
`activities` missing

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-clients#30]
See https://github.com/graphhopper/directions-api-clients/blob/master/swagger.json#L1158 vs. documentation: https://graphhopper.com/api/1/docs/route-optimization/#objectives

Also the documentation should list all and not just 3:

> The objective value specifies whether you want to just optimize vehicles, transport_time or completion_time

**Comment by karussell** [comment]
Have also removed the old Algorithm object: https://github.com/graphhopper/directions-api-clients/commit/c955d19164faecac218b370bb177759e49558ce0

**Comment by oblonski** [comment]
👍

**Comment by oblonski** [comment]
Mortada also mentioned smth regarding swagger and client yesterday. Did you also take this into account?

**Comment by oblonski** [comment]
I am not 100% sure what he meant
