### ISSUE TITLE
failed to clone from git- client invalid username or password 

### ISSUE THREAD

**Issue by kushjoshi26** [graphhopper/directions-api-clients#36]
![graphclient](https://user-images.githubusercontent.com/48751765/60753212-b3412500-9fec-11e9-9f74-e9ecee4e1252.PNG)

**Comment by karussell** [comment]
This is likely some local setting problem. Please also describe your problem (include what you tried step by step and what you expect) otherwise we cannot help.

**Comment by kushjoshi26** [comment]
first, download  SwaggerClient-php from GitHub and replace composer.json with 
{
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/graphhopper/directions-api-client.git"
    }
  ],
  "require": {
    "graphhopper/directions-api-client": "*@dev"
  }
}
then simply run composer install
