### ISSUE TITLE
Deployment section like in core

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-clients#7]
I have fixed this but cannot push into this repo.

**Comment by boldtrn** [comment]
Sorry, added you as contributor.

**Comment by karussell** [comment]
No problem :) but it is still not working ... but not sure - it could be also my fault

**Comment by boldtrn** [comment]
Mhm, you have push access to the repository. You could also create a PR?

**Comment by karussell** [comment]
Worked now. My fault ... I often use the wrong config for ssh access (instead of repo.git ending I use repo/)
