### ISSUE TITLE
Move to gh org

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-clients#9]
I would like to make this repo more official to avoid confusion and propose wider usage. Also we have to deprecate https://github.com/graphhopper/directions-api-clients-route-optimization

Can you try to move or rename this repo to:

`graphhopper/directions-api-clients`

**Comment by karussell** [comment]
- [ ] maybe remove java & js as we have special clients [here](https://github.com/graphhopper/directions-api-java-client) and [here](https://github.com/graphhopper/directions-api-js-client)?
 - [ ] move repo
 - [ ] update docu
 - [ ] deprecate route opt repo

**Comment by oblonski** [comment]
I think we need to deprecate [this](https://github.com/graphhopper/directions-api-clients-route-optimization) and [this](https://github.com/graphhopper/directions-api-java-client)? Correct?

**Comment by oblonski** [comment]
What is again the difference between this here and [this](https://github.com/graphhopper/directions-api-clients-route-optimization)?

**Comment by karussell** [comment]
The java client you linked contains stuff not possible with this java client here e.g. an optimized Matrix client.

> What is again the difference between this here and this?

The idea is to have one client for all APIs, [this](https://github.com/graphhopper/directions-api-clients-route-optimization) is just for the route optimization api.

So the idea is to use this repo as main entry and for Java and JS link to the manual improved once.

**Comment by oblonski** [comment]
> Java and JS link to the manual improved once

Does this mean that the java opt client wont be here, but elsewhere?

**Comment by karussell** [comment]
> Does this mean that the java opt client wont be here, but elsewhere?

Probably better if all is at one place ... hmmh, or better: we have to decide if we go for "a separate repo per language" (easier for the user) or one repo for all languages (easier for us)

**Comment by oblonski** [comment]
I do not mind if there is a separate client for each API since you can import them easily into a single project anyway. However, two or three different clients for the same API is silly.

**Comment by boldtrn** [comment]
Just moved the repo

**Comment by karussell** [comment]
Thanks!

**Comment by karussell** [comment]
Everything should be done now
